rust/rustup.sha1

Small checksum update for building Rust image.

Update rustup checksum

---

sbt-docker/Dockerfile
sbt-docker/README.md

Add sbt-docker image

---

rvi/README.md

[PRO-1210](https://advancedtelematic.atlassian.net/browse/PRO-1210)

Update RVI README instructions

---

rust/Dockerfile

Resolves [PRO-1284](https://advancedtelematic.atlassian.net/browse/PRO-1284)

Add musl-tools to Rust Dockerfile

---

rust-cross/Dockerfile
rust-cross/config

Resolves [PRO-1435](https://advancedtelematic.atlassian.net/browse/PRO-1435)

Add Dockerfile for cross-compiling Rust to ARM MUSL

---

rust/Dockerfile

Resolves [PRO-1306](https://advancedtelematic.atlassian.net/browse/PRO-1306)

Set default Rust toolchain to 1.10.0

---

rust-cross/Dockerfile
rust-cross/README.md
rust-cross/config

Updated as part of [PRO-2013](https://advancedtelematic.atlassian.net/browse/PRO-2013).

Update rust-cross Dockerfile to use ubuntu:precise

---

rust/Dockerfile

Part of [PRO-553](https://advancedtelematic.atlassian.net/browse/PRO-553).

Link to openssl dynamically by default

---

rvi/backend.rvi.config

Resolves [PRO-2429](https://advancedtelematic.atlassian.net/browse/PRO-2429)

Use JSON encoding with RVI Core port 8810

---

rust/build.sh

Resolves [PRO-2614](https://advancedtelematic.atlassian.net/browse/PRO-2614).
@heartsucker: I left out the versions array stuff as we don't want to rebuild old images each time.

Tag nightly rust images with date

---

qemu-system-x86_64/Dockerfile

```
docker images | grep qemu
advancedtelematic/qemu-system-x86_64     latest              55fd1914348f        8 minutes ago       291 MB
advancedtelematic/qemu                   latest              47fcf211b215        4 months ago        2.74 GB
```

Add qemu-system-x86_64.

---

bitbakery/Dockerfile
bitbakery/run.sh

- run as root instead, passing the user id
- switch to debian image

fix user permissions

---

qemu-system-x86_64/Dockerfile

bump qemu-system version to 2.9.0

---

bitbakery/Dockerfile
bitbakery/run.sh

- bring back missing deps
- make built image configurable
- add public cache (overridable)
- remove temporary work by default
- remove gnutls patch (let the system providing the sources handle
patches)

align with updater-repo

---

doctools/Dockerfile
doctools/README.md

Minor doctools fixes, landscape report support

---

swagger2markup/Dockerfile

Just a utility I use for docs, dockerized for convenience.

Add swagger2markup dockerized

---

bitbakery/Dockerfile
bitbakery/bitbake.sh

- switch to debian stretch slim

streamline config parameters

---

dhall-json/Dockerfile
dhall-json/Makefile

Signed-off-by: Alex Humphreys <alex.humphreys@here.com>

Add dhall-json dockerfile

---

npm/Dockerfile
npm/Makefile

Signed-off-by: Jerry Trieu <jerry.trieu@here.com>

Update npm image

---

dhall/Dockerfile
dhall/Makefile

Signed-off-by: Alex Humphreys <alex.humphreys@here.com>

Add dhall dockerfile

---

go-dnsmasq/Dockerfile
go-dnsmasq/Makefile

Add go-dnsmasq

---

.ort.yml

https://artifactory.in.here.com/artifactory/here-oss-local/job-results/7374/dockerfiles-bb0dd955363951496b7b0a915d97a87ba6fc14e5-2019-08-13-scan-report.html

Exluding documentation tools
